### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by aidenrrourke** [jean343/styless#20]
```
box-shadow: if(not @disabled, inset 0 0 0 30px rgba(255, 255, 255, 0.5));
```

When trying to use the not boolean less operator the style doesn't show up.

**Comment by jean343** [comment]
@aidenrrourke, I implemented the `not` part of your query, the following now works:
`box-shadow: if(not (@disabled), inset 0 0 0 30px red);`

The `rgba()` still does not work inside an `if`. I will fix it later, thanks!

**Comment by jean343** [comment]
The `rgba` part is done in version `1.4.7`.
Thanks for upgrading!
