### ISSUE TITLE
Caching issues with less imports

### ISSUE THREAD

**Issue by Kombustor** [jean343/styless#68]
First of all, thanks for creating Styless, it's awesome. 

I think I'm having a caching issue. I import variables from a .less file according to @jean343's [stackoverflow-post](https://stackoverflow.com/a/59472390/10900507). He also mentions to 
> Do not forget to delete the .cache folder for the effects to take place.

But I'm not sure which `.cache` folder is meant, as there is no such folder in my project root or node_modules folder.
This could be the issue that the variables declared before first loading them via babel are working, and the new ones are not.

**Comment by Kombustor** [comment]
I found a solution: As I'm using NextJS babel doesn't use the default node_modules/.cache folder but rather a custom NextJS directory. The cache can be disabled as explained [here](https://github.com/zeit/next.js/issues/3164).

**Comment by jean343** [comment]
Thank you @Kombustor, I appreciate your feedback.
I did mention `.cache` as it was the default cache location for Parcel, it will differ to different locations as you correctly pointed out.
